mysite/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tour.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "Minh Đức Tourist Administration"

tour/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('contact/', views.contact, name="contact"),
    path('destinations/', views.destination, name="destinations"),
    path('destinations/<slug>/', views.tour_list, name="tours"),
    path('tour-detail/<int:pk>/', views.tour_detail, name="tour-detail"),
    path('booking-successful/', views.book_successful, name="book-successful"),
    path('about/', views.about, name="about"),
    path('search-results/', views.SearchResultsView.as_view(), name="search"),

]

tour/models.py
from django.db import models
from django.shortcuts import reverse
import datetime
from django.core.exceptions import ValidationError
from django.utils.html import mark_safe
# Create your models here.

REGION_CHOICES = [
    ('B', 'Miền Bắc'),
    ('T', 'Miền Trung'),
    ('N', 'Miền Nam')
]


class Destination(models.Model):
    name = models.CharField(max_length=200)
    region = models.CharField(choices=REGION_CHOICES, max_length=1)
    image = models.ImageField(null=True, blank=True)
    hot = models.BooleanField(default=True)

    def __str__(self):
        return self.name

    @property  # tránh bị lỗi trang nếu như một ảnh bị xoá
    def imageURL(self):  # giờ đây nó sẽ chỉ hiển thị một khung ảnh trống trên template
        try:  # trên template thay destination.image.url = destination.imageURL
            url = self.image.url
        except:
            url = ''
        return url

    def get_absolute_url(self):
        return reverse("tours", kwargs={'slug': self.name})  # ("app_name: url_name") - có thể ko cần app name


class TourGuide(models.Model):
    name = models.CharField(max_length=200)
    gender = models.CharField(max_length=1, null=True, choices=[('1', 'nam'), ('2', 'nữ')])
    image = models.ImageField(null=True, blank=True)
    birth = models.DateField(null=True)
    phone = models.CharField(max_length=15)
    email = models.EmailField(max_length=200)
    english = models.BooleanField(default=False)
    japanese = models.BooleanField(default=False)
    korean = models.BooleanField(default=False)
    chinese = models.BooleanField(default=False)
    french = models.BooleanField(default=False)
    russian = models.BooleanField(default=False)
    spanish = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    @property
    def thumbnail_preview(self):
        if self.image:
            return mark_safe('<img src="{}" width="200" height="200" />'.format(self.image.url))
        return ""


class Tour(models.Model):
    destination = models.ForeignKey(Destination, on_delete=models.CASCADE)
    departure_place = models.CharField(max_length=200)
    visit_places = models.CharField(max_length=200, null=True, blank=True)
    price = models.DecimalField(max_digits=8, decimal_places=0)
    num_seats = models.SmallIntegerField()
    departure_date = models.DateField()
    num_days = models.SmallIntegerField()
    tour_guide = models.ForeignKey(TourGuide, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return "{} - {}".format(self.departure_place, self.destination)


class ImageTour(models.Model):
    image = models.ImageField(null=True, blank=True)
    tour = models.ForeignKey(Tour, on_delete=models.CASCADE)

    def __str__(self):
        return self.image.url

    @property               # tránh bị lỗi trang nếu như một ảnh bị xoá
    def imageURL(self):     # giờ đây nó sẽ chỉ hiển thị một khung ảnh trống trên template
        try:                # trên template thay destination.image.url = destination.imageURL
            url = self.image.url
        except:
            url = ''
        return url


class Schedule(models.Model):
    activity = models.TextField(null=True, blank=True)
    tour = models.ForeignKey(Tour, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.id)


class Book(models.Model):
    tour = models.ForeignKey(Tour, on_delete=models.SET_NULL, blank=True, null=True)
    customer_name = models.CharField(max_length=200)
    customer_phone = models.CharField(max_length=15)
    customer_email = models.EmailField(max_length=200)
    custumer_addess = models.CharField(max_length=200)
    number_people = models.SmallIntegerField()
    total_pay = models.DecimalField(max_digits=15, decimal_places=0, null=True, blank=True)
    date_booked = models.DateTimeField(auto_now_add=True)  # auto_now_add sẽ tự động thêm datetime tại thời điểm đối tượng đc thêm / auto_now sẽ tự thay đổi datetime hiện tại mỗi khi đối tượng đc save

    def save(self, *args, **kwargs):
        if self.number_people > self.tour.num_seats:
            raise ValueError('Số lượng người vượt quá số chỗ còn nhận!')
        else:
            self.tour.num_seats = self.tour.num_seats - self.number_people
            self.tour.save()
        if self.total_pay == None:
            self.total_pay = self.tour.price * self.number_people

        super(Book, self).save(*args, **kwargs)

    # def __str__(self):
    #     return str(self.id)


class Feedback(models.Model):
    cus_name = models.CharField(max_length=200)
    cus_email = models.EmailField(max_length=200)
    subject = models.CharField(max_length=200)
    message = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.subject

tour/views.py
from django.shortcuts import render, redirect
from .models import *
from django.http import HttpResponseRedirect
from django.views.generic import (ListView, DetailView)
from django.db.models import Q
# sending email
from django.conf import settings
from django.core.mail import EmailMessage
from django.template.loader import render_to_string  # render template to body of email
# pagination
from django.core.paginator import EmptyPage, Paginator
# Create your views here.


def about(request):
    context = {
        'title': ' Giới Thiệu - Vietravel',
        'active2': 'active'
    }
    return render(request, 'about.html', context)


def contact(request):
    if request.method == "POST":
        name = request.POST['name']
        email = request.POST['email']
        subject = request.POST['subject']
        message = request.POST['message']
        feedback = Feedback(cus_name=name, cus_email=email, subject=subject, message=message)
        feedback.save()
        msg = "'Bạn đã gửi phản hồi thành công! Chúng tôi sẽ trả lời bạn trong 24h.'"

        return render(request, 'contact.html', {'msg': msg, 'title': 'Liên Hệ - Vietravel', 'active4': 'active'})

    context = {
        'title': 'Liên Hệ - Vietravel',
        'active4': 'active',
    }
    return render(request, 'contact.html', context)


def destination(request):
    destinations = Destination.objects.all()
    paginator = Paginator(destinations, 3)
    page_number = request.GET.get('page', 1)  # set default is page 1
    try:
        page_obj = paginator.page(page_number)
    except EmptyPage:
        page_obj = paginator.page(paginator.num_pages)  # nếu số trang ko tồn tại thì lấy trang cuối cùng
    context = {
        'destinations': destinations,   #: page_obj if use pagination
        'title': 'Điểm Đến - Vietravel',
        'active3': 'active',
        'page_obj': 'page_obj'
    }
    return render(request, 'destinations.html', context)


def index(request):
    hot_destinations = Destination.objects.filter(hot=True)[:10]  # lấy 10 cái đầu tiên
    # lấy ra list các giá trị của cột image có show=True. If you only pass in a single field, you can also pass in the 'flat' parameter. If True, this will mean the returned results are single values, rather than one-tuples
    destinations = Destination.objects.values_list('name', flat=True).distinct()  # distinct() loại bỏ các giá trị trùng lặp
    context = {
        'hot_destinations': hot_destinations,
        'title': 'Trang Chủ - Vietravel',
        'active1': 'active',
        'destinations': destinations,
    }
    return render(request, 'index.html', context)


class SearchResultsView(ListView):
    model = Tour
    template_name = 'search_results.html'

    def get_queryset(self):
        query = self.request.GET.get('selectpicker')
        date = self.request.GET.get('selectdate')
        if date == '':
            object_list = Tour.objects.filter(destination__name__icontains=query)
        else:
            object_list = Tour.objects.filter(Q(destination__name__icontains=query), Q(departure_date__gte=date))

        return object_list


def tour_list(request, slug):
    tours = Tour.objects.filter(destination__name=slug)  # https://stackoverflow.com/questions/27421794/retrieve-foreign-key-object-field-django
    context = {
        'title': 'Tours - Vietravel',
        'tours': tours,
        'destination': slug,
    }
    return render(request, 'tours.html', context)


def tour_detail(request, pk):
    tour = Tour.objects.get(id=pk)
    context = {
        'title': 'Chi tiết Tour - Vietravel',
        'tour': tour,
    }
    if request.method == "POST":
        name = request.POST['inputName']
        phone = request.POST['inputPhone']
        email = request.POST['inputEmail']
        address = request.POST['inputAddress']
        people = request.POST['inputPeople']
        total = tour.price*int(people)
        book = Book(customer_name=name, customer_phone=phone, customer_email=email, custumer_addess=address, tour=tour, number_people=int(people), total_pay=total)
        book.save()
        request.session['customer_email'] = email
        request.session['tour_id'] = pk
        return redirect('book-successful')

    return render(request, 'tour_detail.html', context)


def book_successful(request):
    customer_email = request.session.get('customer_email')
    tour_id = request.session.get('tour_id')
    tour = Tour.objects.get(id=tour_id)
    template = render_to_string('template_email.html', {'tour_name': tour.visit_places, 'date': tour.departure_date})

    email = EmailMessage(
        'Vietravel - Đơn đặt tour',
        template,
        settings.EMAIL_HOST_USER,
        [customer_email]
    )
    email.fail_silently = False
    email.send()

    context = {
        'title': 'Cảm ơn bạn - Vietravel',
    }
    return render(request, 'book_successful.html', context)

tour/templates/book_successful.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<!-- about breadcrumb -->
<section class="w3l-about-breadcrumb text-left">
  <div class="breadcrumb-bg breadcrumb-bg-about py-sm-5 py-4">
    <div class="container">
      <h2 class="title">Thank you !!! </h2>
    </div>
  </div>
</section>
<!-- //about breadcrumb -->
<!--  Work gallery section -->
<section class="grids-1 py-5">
    <div class="container mt-5">
        <h2 style="color:green; font-style: italic;"> Bạn đã đặt tour thành công !</h2>
    </div>
</section>


{% endblock content %}

tour/templates/search_results.html
  {% extends 'base.html' %}
  {% load static %}
  {% block content %}

  <!-- about breadcrumb -->
  <section class="w3l-about-breadcrumb text-left">
    <div class="breadcrumb-bg breadcrumb-bg-about py-sm-5 py-4">
      <div class="container">
        <h2 class="title">Tours </h2>
        <ul class="breadcrumbs-custom-path mt-2">
          <li><a href="{% url 'index' %}">Trang Chủ</a></li>
          <li class="active"><span class="fa fa-arrow-right mx-2" aria-hidden="true"></span> Tours </li>
        </ul>
      </div>
    </div>
  </section>
  <!-- //about breadcrumb -->

  <!--/grids-->
  <section class="w3l-grids-3 py-5">
    <div class="container py-md-5">
      <div class="title-content text-left mb-lg-5 mb-4">
        <h6 class="sub-title">Kết quả tìm kiếm:</h6>
      </div>
      <div class="row bottom-ab-grids">

        {% for tour in object_list %}
        <div class="col-12 subject-card mt-4">
          <div class="subject-card-header p-4">
            <a href="{% url 'tour-detail' tour.id %}" class="card_title p-lg-4d-block">
              <div class="row align-items-center">
                <div class="col-6">
                  {% with tour.imagetour_set.all|first as image %}         <!--lấy item đầu tiền trong ds các item liên quan đến tour này-->
                  <img src="{{ image.imageURL }}" class="img-fluid" style="max-width: 100%;object-fit: cover">
                  {% endwith %}
                </div>
                <div class="col-6 subject-content mt-sm-0 mt-4">
                  <h4>{{ tour.visit_places }} </h4>
                  <div class="dst-btm">
                    <h6 class=""> Giá: <span style="padding-left:10px">{{tour.price}}đ</span> </h6> </br>
                    <h6 class=""> Số chỗ: {{tour.num_seats}} </h6>
                    <h6 class=""> Số ngày: {{tour.num_days}} </h6>
                    <h6 class=""> Ngày khởi hành: {{tour.departure_date|date:'d/m/Y'}} </h6>
                    <h6 class=""> Nơi khởi hành: {{tour.departure_place}} </h6>
                  </div>
                  <p class="sub-para">Bao gồm khách sạn và ăn sáng</p>
                </div>
              </div>
            </a>
          </div>
        </div>
        {% endfor %}
        

      </div>
    </div>
  </section>
  <!--//grids-->
  <!-- testimonials -->
  <section class="w3l-clients" id="clients">
    <!-- /grids -->
    <div class="cusrtomer-layout py-5">
      <div class="container py-lg-4 py-md-3 pb-lg-0">
        <div class="heading text-center mx-auto">
          <h6 class="sub-title text-center">Here’s what they have to say</h6>
          <h3 class="hny-title mb-md-5 mb-4">our clients do the talking</h3>
        </div>
        <!-- /grids -->
        <div class="testimonial-width">
          <div id="owl-demo1" class="owl-two owl-carousel owl-theme">
            <div class="item">
              <div class="testimonial-content">
                <div class="testimonial">
                  <blockquote>
                    <span class="fa fa-quote-left" aria-hidden="true"></span>
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit beatae laudantium
                    voluptate rem ullam dolore nisi voluptatibus esse quasi. Integer sit amet .Lorem ipsum dolor sit
                    amet adipisicing elit. Laborum dolor facere ipsum adipisicingelit.
                  </blockquote>
                  <div class="testi-des">
                    <div class="test-img"><img src="{% static 'images/c1.jpg' %}" class="img-fluid" alt="client-img">
                    </div>
                    <div class="peopl align-self">
                      <h3>Rohit Paul</h3>
                      <p class="indentity">Example City</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="item">
              <div class="testimonial-content">
                <div class="testimonial">
                  <blockquote>
                    <span class="fa fa-quote-left" aria-hidden="true"></span>
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit beatae laudantium
                    voluptate rem ullam dolore nisi voluptatibus esse quasi. Integer sit amet .Lorem ipsum dolor sit
                    amet adipisicing elit. Laborum dolor facere ipsum adipisicingelit.
                  </blockquote>
                  <div class="testi-des">
                    <div class="test-img"><img src="{% static 'images/c2.jpg' %}" class="img-fluid" alt="client-img">
                    </div>
                    <div class="peopl align-self">
                      <h3>Shveta</h3>
                      <p class="indentity">Example City</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="item">
              <div class="testimonial-content">
                <div class="testimonial">
                  <blockquote>
                    <span class="fa fa-quote-left" aria-hidden="true"></span>
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit beatae laudantium
                    voluptate rem ullam dolore nisi voluptatibus esse quasi. Integer sit amet .Lorem ipsum dolor sit
                    amet adipisicing elit. Laborum dolor facere ipsum adipisicingelit.
                  </blockquote>
                  <div class="testi-des">
                    <div class="test-img"><img src="{% static 'images/c3.jpg' %}" class="img-fluid" alt="client-img">
                    </div>
                    <div class="peopl align-self">
                      <h3>Roy Linderson</h3>
                      <p class="indentity">Example City</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="item">
              <div class="testimonial-content">
                <div class="testimonial">
                  <blockquote>
                    <span class="fa fa-quote-left" aria-hidden="true"></span>
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit beatae laudantium
                    voluptate rem ullam dolore nisi voluptatibus esse quasi. Integer sit amet .Lorem ipsum dolor sit
                    amet adipisicing elit. Laborum dolor facere ipsum adipisicingelit.
                  </blockquote>
                  <div class="testi-des">
                    <div class="test-img"><img src="{% static 'images/c4.jpg' %}" class="img-fluid" alt="client-img">
                    </div>
                    <div class="peopl align-self">
                      <h3>Mike Thyson</h3>
                      <p class="indentity">Example City</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- /grids -->
    </div>
    <!-- //grids -->
  </section>
  <!-- //testimonials -->

  {% endblock content %}

tour/templates/template_email.html
Chào bạn!

Chúng tôi vừa nhận được đơn đặt tour du lịch của bạn, Tour: {{tour_name}}.

Cảm ơn bạn đã tin tưởng và sử dụng dịch vụ của công ty Vietravel. Rất vui được đồng hành cùng bạn trong chuyến du lịch ngày {{date|date:'d/m/Y'}} sắp tới.

Trân trọng,
Công ty Vietravel.

tour/templates/tour_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<!-- about breadcrumb -->
<section class="w3l-about-breadcrumb text-left">
  <div class="breadcrumb-bg breadcrumb-bg-about py-sm-5 py-4">
    <div class="container">
      <h2 class="title">Chi tiết tour </h2>
      <ul class="breadcrumbs-custom-path mt-2">
        <li><a href="{% url 'index' %}">Trang Chủ</a></li>
        <li class="active"><span class="fa fa-arrow-right mx-2" aria-hidden="true"></span> Tour </li>
        <li class="active"><span class="fa fa-arrow-right mx-2" aria-hidden="true"></span> {{tour.departure_place}} ->
          {{tour.destination.name}} </li>
      </ul>
    </div>
  </div>
</section>
<!-- //about breadcrumb -->
<!--  Work gallery section -->
<section class="grids-1 py-5">
  <div class="container mt-3">
    <div class="row">
      <div class="col mb-4">
        <h3>Chi tiết tour du lịch: {{tour.visit_places}}</h3>
      </div>
    </div>
    <div class="row">
      <div class="col-12 col-md-6">
        {% for photo in tour.imagetour_set.all %}
        <div class="img-banner mt-1">
          <a href="{{ photo.imageURL }}"><img src="{{ photo.imageURL }}" alt="" style="max-width: 100%;"></a>
        </div>
        {% endfor %}
      </div>
      <div class="col-12 col-md-6">
        <div class="card p-3">
          <div>
            <span>Ngày khởi hành: {{tour.departure_date|date:'d/m/Y'}} </span>
          </div>
          <div class="mt-1">
            <span>Nơi Khởi Hành: {{tour.departure_place}} </span>
          </div>
          <div class="mt-1">
            <span>Số ngày: {{tour.num_days}} </span>
          </div>
          <div class="d-flex justify-content-between">
            <div>
              <p id="price" style="color: red;font-weight: bold;"> {{tour.price}}đ/người</p>
              <span>Số chỗ còn nhận: <span style="color: red;">{{tour.num_seats}}</span></span>
            </div>
          </div>
        </div>
        <div class="card p-2">
          <form action="" method="POST" >
          {% csrf_token %}
            <h4 class="p-2 text-center">Đặt tour ngay</h4>
            <input type="hidden" name="toud-id" value="{{tour.id}}">
            <div class="form-group">
              <input type="text" class="form-control" name="inputName" id="inputName" placeholder="Tên của bạn" required>
            </div>
            <div class="form-group">
              <input type="text" class="form-control" name="inputPhone" id="inputPhone" placeholder="Số điện thoại" required>
            </div>
            <div class="form-group">
              <input type="email" class="form-control" name="inputEmail" id="inputEmail" placeholder="Email" required>
            </div>
            <div class="form-group">
              <input type="text" class="form-control" name="inputAddress" id="inputAddress" placeholder="Địa chỉ" required>
            </div>
            <div class="form-group">
              <input type="number" min="1" max="{{tour.num_seats}}" class="form-control" name="inputPeople" id="inputPeople"
                placeholder="Số người" required>
            </div>
            <div class="d-flex justify-content-between">
              <label>Tổng tiền: <span id="total" style="color: red; font-weight: bold"></span></label>
              <button type="submit" class="btn btn-danger ">Đặt tour</button>
            </div>
          </form>
        </div>
        {% comment %} <div class="container" style="background-color: rgb(221, 204, 204);">
          <h4 class="p-3 text-center mt-2">CHƯƠNG TRÌNH TOUR DU LỊCH</h4>
        </div> {% endcomment %}
      </div>
    </div>
  </div>
  <div class="container mt-3">
    <div class="row">
      <div class="col">
        <div class="container" style="background-color: rgb(221, 204, 204);">
          <h4 class="p-3 text-center">LỊCH TRÌNH TOUR</h4>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col">
        {% for x in tour.schedule_set.all %}
        <div class="container card p-2">
          <h4>Ngày {{ forloop.counter }}</h4>
          <p>{{ x.activity|linebreaks }}</p>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</section>
<!--  //Work gallery section -->
<!-- grids block 5 -->
<script>
  document.getElementById("inputPeople").addEventListener('change', ()=>{
    let a = document.getElementById("price").textContent;
    let b = (a.slice(0,a.indexOf('đ'))).replaceAll(',','');
    let c =  (document.getElementById("inputPeople").value) * b;
    console.log(c);
    document.getElementById("total").innerHTML = Number((parseInt(c)).toFixed(1)).toLocaleString() + 'đ'; 
  });
</script>

{% endblock content %}

tour/templates/tours.html
  {% extends 'base.html' %}
  {% load static %}
  {% block content %}

    <!-- about breadcrumb -->
  <section class="w3l-about-breadcrumb text-left">
    <div class="breadcrumb-bg breadcrumb-bg-about py-sm-5 py-4">
      <div class="container">
        <h2 class="title">Tất cả điểm đến </h2>
        <ul class="breadcrumbs-custom-path mt-2">
          <li><a href="{% url 'index' %}">Trang Chủ</a></li>
          <li class="active"><span class="fa fa-arrow-right mx-2" aria-hidden="true"></span> Điểm Đến </li>
        </ul>
      </div>
    </div>
  </section>
  <!-- //about breadcrumb -->

  <!--/grids-->
  <section class="w3l-grids-3 py-5">
    <div class="container py-md-5">
      <div class="title-content text-left mb-lg-5 mb-4">
        <h6 class="sub-title">Tham quan</h6>
        <h3 class="hny-title">Tour đi: {{ destination }}</h3>
      </div>
      <div class="row bottom-ab-grids">

        {% for tour in tours %}
        <div class="col-12 subject-card mt-4">
          <div class="subject-card-header p-4">
            <a href="{% url 'tour-detail' tour.id %}" class="card_title p-lg-4d-block">
              <div class="row align-items-center">
                <div class="col-6">
                  {% with tour.imagetour_set.all|first as image %}         <!--lấy item đầu tiền trong ds các item liên quan đến tour này-->
                  <img src="{{ image.imageURL }}" class="img-fluid" style="max-width: 100%;object-fit: cover">
                  {% endwith %}
                </div>
                <div class="col-6 subject-content mt-sm-0 mt-4">
                  <h4>{{ tour.visit_places }} </h4>
                  <div class="dst-btm">
                    <h6 class=""> Giá: <span style="padding-left:10px">{{tour.price}}đ</span> </h6> </br>
                    <h6 class=""> Số chỗ: {{tour.num_seats}} </h6>
                    <h6 class=""> Số ngày: {{tour.num_days}} </h6>
                    <h6 class=""> Ngày khởi hành: {{tour.departure_date|date:'d/m/Y'}} </h6>
                    <h6 class=""> Nơi khởi hành: {{tour.departure_place}} </h6>
                  </div>
                  <p class="sub-para">Bao gồm khách sạn và ăn sáng</p>
                </div>
              </div>
            </a>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </section>
  <!--//grids-->
  <!-- testimonials -->
  <section class="w3l-clients" id="clients">
    <!-- /grids -->
    <div class="cusrtomer-layout py-5">
      <div class="container py-lg-4 py-md-3 pb-lg-0">
        <div class="heading text-center mx-auto">
          <h6 class="sub-title text-center">Here’s what they have to say</h6>
          <h3 class="hny-title mb-md-5 mb-4">our clients do the talking</h3>
        </div>
        <!-- /grids -->
        <div class="testimonial-width">
          <div id="owl-demo1" class="owl-two owl-carousel owl-theme">
            <div class="item">
              <div class="testimonial-content">
                <div class="testimonial">
                  <blockquote>
                    <span class="fa fa-quote-left" aria-hidden="true"></span>
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit beatae laudantium
                    voluptate rem ullam dolore nisi voluptatibus esse quasi. Integer sit amet .Lorem ipsum dolor sit
                    amet adipisicing elit. Laborum dolor facere ipsum adipisicingelit.
                  </blockquote>
                  <div class="testi-des">
                    <div class="test-img"><img src="assets/images/c1.jpg" class="img-fluid" alt="client-img">
                    </div>
                    <div class="peopl align-self">
                      <h3>Rohit Paul</h3>
                      <p class="indentity">Example City</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="item">
              <div class="testimonial-content">
                <div class="testimonial">
                  <blockquote>
                    <span class="fa fa-quote-left" aria-hidden="true"></span>
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit beatae laudantium
                    voluptate rem ullam dolore nisi voluptatibus esse quasi. Integer sit amet .Lorem ipsum dolor sit
                    amet adipisicing elit. Laborum dolor facere ipsum adipisicingelit.
                  </blockquote>
                  <div class="testi-des">
                    <div class="test-img"><img src="assets/images/c2.jpg" class="img-fluid" alt="client-img">
                    </div>
                    <div class="peopl align-self">
                      <h3>Shveta</h3>
                      <p class="indentity">Example City</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="item">
              <div class="testimonial-content">
                <div class="testimonial">
                  <blockquote>
                    <span class="fa fa-quote-left" aria-hidden="true"></span>
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit beatae laudantium
                    voluptate rem ullam dolore nisi voluptatibus esse quasi. Integer sit amet .Lorem ipsum dolor sit
                    amet adipisicing elit. Laborum dolor facere ipsum adipisicingelit.
                  </blockquote>
                  <div class="testi-des">
                    <div class="test-img"><img src="assets/images/c3.jpg" class="img-fluid" alt="client-img">
                    </div>
                    <div class="peopl align-self">
                      <h3>Roy Linderson</h3>
                      <p class="indentity">Example City</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="item">
              <div class="testimonial-content">
                <div class="testimonial">
                  <blockquote>
                    <span class="fa fa-quote-left" aria-hidden="true"></span>
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit beatae laudantium
                    voluptate rem ullam dolore nisi voluptatibus esse quasi. Integer sit amet .Lorem ipsum dolor sit
                    amet adipisicing elit. Laborum dolor facere ipsum adipisicingelit.
                  </blockquote>
                  <div class="testi-des">
                    <div class="test-img"><img src="assets/images/c4.jpg" class="img-fluid" alt="client-img">
                    </div>
                    <div class="peopl align-self">
                      <h3>Mike Thyson</h3>
                      <p class="indentity">Example City</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>


          </div>
        </div>
      </div>
      <!-- /grids -->
    </div>
    <!-- //grids -->
  </section>
  <!-- //testimonials -->

  {% endblock content %}